# .github/workflows/release.yml

name: Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # necessário para criar releases e enviar assets

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version from fxmanifest.lua
        id: get_version
        run: |
          # Extrai a versão do fxmanifest.lua
          VERSION=$(grep -Po "(?<=version ')[^']+" fxmanifest.lua)
          # Exporta a saída para ser usada nos próximos passos
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name:     ${{ steps.get_version.outputs.version }}
          release_name: CipherScanner V${{ steps.get_version.outputs.version }}
          body:         Automated release for version ${{ steps.get_version.outputs.version }}
          draft:        false
          prerelease:   false

      - name: Package ZIP
        run: |
          zip -r "CipherScanner-${{ steps.get_version.outputs.version }}.zip" . \
            -x ".git/**" "node_modules/**" ".github/**"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url:         ${{ steps.create_release.outputs.upload_url }}
          asset_path:         ./CipherScanner-${{ steps.get_version.outputs.version }}.zip
          asset_name:         CipherScanner-${{ steps.get_version.outputs.version }}.zip
          asset_content_type: application/zip
