# .github/workflows/release.yml

name: Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # necessário para criar releases e enviar assets

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version from config.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' config.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          token:        ${{ secrets.GH_TOKEN }}
          tag_name:     v${{ env.VERSION }}
          release_name: CipherScanner V${{ env.VERSION }}
          body:         "Automated release v${{ env.VERSION }}"
          draft:        false
          prerelease:   false

      - name: Package ZIP
        run: |
          zip -r "CipherScanner-${{ env.VERSION }}.zip" . \
            -x ".git/**" "node_modules/**"

      - name: Upload Release Asset
        id: upload_asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url:        ${{ steps.create_release.outputs.upload_url }}
          asset_path:        ./CipherScanner-${{ env.VERSION }}.zip
          asset_name:        CipherScanner-${{ env.VERSION }}.zip
          asset_content_type: application/zip
          token:             ${{ secrets.GH_TOKEN }}
